export const ActionTypes = {
  SET_BOOK_CATEGORIES: "SET_BOOK_CATEGORIES",
  REMOVE_SELECTED_BOOK_CATEGORY: "REMOVE_SELECTED_BOOK_CATEGORY",

  SELECTED_BOOK: "SELECTED_BOOK",

  SET_LOADING: "SET_LOADING",
};
